spring:
  application:
    name: JhipsterSampleApplication
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      database: jhipsterSampleApplication
      uri: mongodb://localhost:27017/jhipsterSampleApplication
logging:
  level:
    com:
      mycompany:
        myapp: INFO
